export const customNickname = {
}

export const teamMember = {
    "mcload": "MECH Nicky",
    "cyshek": "MECH Isabella",
    "mswangaa": "MECH Martin",
    "pichong": "MECH Victoria",
    "hctseac": "MECH Hillary",
    "nktsangaa": "MECH Ken",
    "kschungad": "MECH Casper",
    "lyychen": "MECH Leo",
    "chlambp": "MECH Chris",
    "yludk": "MECH Lucy",
    "tkzhang": "MECH Moses",
    "kklian": "MECH King",
    "hsschow": "MECH Samson",
    "kcwongby": "HW Ankh",
    "yauyeungaa": "HW Sam",
    "kwqooi": "HW Kylan",
    "wyszeab": "HW Nikki",
    "cyangbn": "HW Danny",
    "mttamaa": "HW Thomas",
    "hwucp": "HW Nature",
    "twangcm": "HW Jonathon",
    "mfsiu": "HW Billy",
    "swcho": "HW Jackie",
    "cychanel": "HW Zoe",
    "tkleungal": "SW Gary",
    "dhcheungaa": "SW Dicaprio",
    "khchengaw": "SW Sartin",
    "syliao": "SW Lycia",
    "cmiu": "SW Rangers",
    "yhhongaa": "SW Henry",
    "cyshihaa": "SW Yiu",
    "cyhobl": "SW Owen",
    "kckoae": "SW Marco",
    "cyangbh": "SW Alvin",
    "ncachong": "SW Adrian",
    "chcham": "SW Chao",
    "cltsuiad": "SW Mavis",
    "sycheungat": "SW Yoyo",
    "cpchanah": "SW Starfall",
    "hmliaf": "SW Jerry",
    "hchloi": "SW CEO Henry",
}

export const exceptionalCase = {
    "tr246135@gmail.com": "SW Starfall",
    "sam07@live.hk": "HW Sam",
    "alexchan815@gmail.com": "SW Chalex"
}